### ISSUE TITLE
Automatic deployment

### ISSUE THREAD

**Issue by wanyamaman** [wanyamaman/eduportal#11]
Successful travis builds on master should automatically deploy.

To be implemented after the following:
- [x] Added Travis CI #8 
- [x] Upgrade to Rails 5 #9 
- [x] Improve model test coverage #10

**Comment by wanyamaman** [comment]
Needs:
- Research on master branch automatic deployment when working with develop branch in travis
- Improved test coverage

**Comment by wanyamaman** [comment]
Switching to Manual deployment for safer management of master.
